SELECT C.CAR_ID, C.CAR_TYPE, ROUND((C.DAILY_FEE * (1-P.DISCOUNT_RATE/100)) * 30 ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C, CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H, CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND P.DURATION_TYPE='30일 이상'
AND P.CAR_TYPE = C.CAR_TYPE AND C.CAR_ID = H.CAR_ID
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
)
GROUP BY CAR_ID
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
