-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I, ANIMAL_OUTS AS O
WHERE I.SEX_UPON_INTAKE LIKE 'INTACT%' AND NOT O.SEX_UPON_OUTCOME LIKE 'INTACT%'
AND I.ANIMAL_ID = O.ANIMAL_ID