-- 기준점수 96이상: S, 연봉 * 0.2 / 90이상: A, 연봉 * 0.15 / 80이상: B, 연봉 * 0.1 / 이외: C, 0

SELECT E.EMP_NO, E.EMP_NAME, 
CASE
    WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
    WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C'
END AS GRADE,
CASE
    WHEN AVG(SCORE) >= 96 THEN SAL * 0.2
    WHEN AVG(SCORE) >= 90 THEN SAL * 0.15
    WHEN AVG(SCORE) >= 80 THEN SAL * 0.1
    ELSE 0
END AS BONUS
FROM HR_EMPLOYEES AS E
JOIN HR_DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY E.EMP_NO;