SELECT sum(G.SCORE) as SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT as D, HR_EMPLOYEES as E, HR_GRADE as G
WHERE D.DEPT_ID = E.DEPT_ID and E.EMP_NO = G.EMP_NO and G.YEAR = 2022
GROUP BY E.EMP_NO
ORDER BY sum(G.SCORE) desc
limit 1;