SELECT concat("/home/grep/src/", B.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD as B, USED_GOODS_FILE as F
WHERE 
    B.BOARD_ID = F.BOARD_ID and
    B.BOARD_ID = 
        (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)
ORDER BY F.FILE_ID desc;